pr:
  branches:
    include:
      - '*'


jobs:
  - job: Scan_Images
    displayName: Build and Scan Images with Trivy
    workspace:
      clean: all # what to clean up before the job runs
    steps:
      - task: PowerShell@2
        displayName: "Clean All Images (Space Required to Build)"
        inputs:
          targetType: 'inline'
          script: |
            docker system prune --all --force
      - task: Bash@3
        displayName: "Clean Other Unused Resources"
        inputs:
          targetType: 'inline'
          script: |
            df -h
            echo now freeing disk space
            sudo rm -rf /usr/local/lib/android # android sdks
            sudo rm -rf /usr/local/.ghcup # haskell stuff
            echo freed up space:
            df -h
      - task: PowerShell@2
        name: archTag
        displayName: "Obtain Latest Arch Tag"
        inputs:
          targetType: 'inline'
          script: |
            $tag=(Invoke-RestMethod "https://gitlab.archlinux.org/archlinux/archlinux-docker/-/tags?format=atom" | Sort-Object -Property updated -Descending | Select-Object -First 1 | Select-Object -ExpandProperty title).Replace("v", [string]::Empty);
            Write-Host "##vso[task.setvariable variable=archTag]$tag"
      - task: Docker@2   
        displayName: "Build Arch Image"
        inputs:
          arguments: --build-arg tag=$(archTag)
          command: build     
          Dockerfile: './Arch/Dockerfile'    
          tags: felsokning/worker-tools:$(Build.BuildId)-arch
      - task: trivy@1
        displayName: "Scan Arch Image"
        inputs:
          docker: false
          exitCode: 0
          image: felsokning/worker-tools:$(Build.BuildId)-arch
          severities: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
