name: build
on:
  pull_request:
    branches:
        - '*'
jobs:
  build_and_scan:
    name: "Build and Scan"
    runs-on: ubuntu-20.04
    steps:
      - name: "Nuke Docker Images"
        run: |
            df -h
            sudo apt install aptitude -y 
            sudo aptitude purge aria2 ansible azure-cli shellcheck rpm xorriso zsync esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable google-cloud-sdk imagemagick libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl mercurial apt-transport-https mono-complete libmysqlclient \
                unixodbc-dev yarn chrpath libssl-dev libxft-dev libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev snmp pollinate libpq-dev postgresql-client ruby-full sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable -y -f
            sudo aptitude purge '~n ^mysql' -f -y 
            sudo aptitude purge '~n ^php' -f -y 
            sudo aptitude purge '~n ^dotnet' -f -y 
            sudo apt-get autoremove --purge -y 
            sudo apt-get autoclean -y
            df -h
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Latest Daily Arch Tag
        id: dailyarchtag
        shell: pwsh
        run: $tag=(Invoke-RestMethod "https://gitlab.archlinux.org/archlinux/archlinux-docker/-/tags?format=atom" | Sort-Object -Property updated -Descending | Select-Object -First 1 | Select-Object -ExpandProperty title).Replace("v", [string]::Empty); Write-Output "tag=$($tag)" >> $env:GITHUB_OUTPUT
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5.1.0
        with:
          build-args: tag=${{ steps.dailyarchtag.outputs.tag }}
          context: ${{ github.workspace }}/Arch
          file: ./Arch/Dockerfile
          push: false
          tags: felsokning/worker-tools:${{ github.sha }}-arch
          labels: ${{ steps.meta.outputs.labels }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/felsokning/worker-tools:${{ github.sha }}-arch'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'