name: build
on:
  pull_request:
    branches:
        - '*'
jobs:
  build_and_scan:
    name: "Build and Scan"
    runs-on: ubuntu-20.04
    steps:
      - name: Space Clean-Up on Runner
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
          docker system prune --all --force
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^ghc-8.*'
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          # deleting 15GB
          rm -rf /usr/share/dotnet/
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "List Files"
        run: ls -l
      - name: Get Latest Daily Arch Tag
        id: dailyarchtag
        shell: pwsh
        run: $tag=(Invoke-RestMethod "https://gitlab.archlinux.org/archlinux/archlinux-docker/-/tags?format=atom" | Sort-Object -Property updated -Descending | Select-Object -First 1 | Select-Object -ExpandProperty title).Replace("v", [string]::Empty); Write-Output "tag=$($tag)" >> $env:GITHUB_OUTPUT
      - name: Build an image from Dockerfile
        working-directory: ./Arch
        run: |
          docker build --build-arg tag=${{ steps.dailyarchtag.outputs.tag }} -t docker.io/felsokning/worker-tools:${{ github.sha }}-arch .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/felsokning/worker-tools:${{ github.sha }}-arch'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'