name: build
on:
  pull_request:
    branches:
        - '*'
jobs:
  build_and_scan:
    name: "Build and Scan"
    runs-on: ubuntu-20.04
    steps:
      - name: Space Clean-Up on Runner
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/hostedtoolcache
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "List Files"
        run: ls -l
      - name: Get Latest Daily Arch Tag
        id: dailyarchtag
        shell: pwsh
        run: $tag=(Invoke-RestMethod "https://gitlab.archlinux.org/archlinux/archlinux-docker/-/tags?format=atom" | Sort-Object -Property updated -Descending | Select-Object -First 1 | Select-Object -ExpandProperty title).Replace("v", [string]::Empty); Write-Output "tag=$($tag)" >> $env:GITHUB_OUTPUT
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5.1.0
        with:
          build-args: tag=${{ steps.dailyarchtag.outputs.tag }}
          context: ${{ github.workspace }}/Arch
          file: ./Arch/Dockerfile
          push: false
          tags: felsokning/worker-tools:${{ github.sha }}-arch
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/felsokning/worker-tools:${{ github.sha }}-arch'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'