name: build
on:
  pull_request:
    branches:
        - '*'
jobs:
  build_and_scan:
    name: "Build and Scan"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "List Files"
        run: ls -l
      - name: Get Latest Daily Arch Tag
        id: dailyarchtag
        shell: bash
        run: |
            sudo apt-get install jq yq
            VERSION=$(curl -s https://gitlab.archlinux.org/archlinux/archlinux-docker/-/tags?format=atom | xq -r '.feed.entry[0].title')
            FIXED_VERSION=$(echo "${VERSION//v}")
            echo "tag=${FIXED_VERSION}" >> "$GITHUB_OUTPUT"
      - name: Build an image from Dockerfile
        working-directory: ./Arch
        run: |
          docker build --build-arg tag=${{ steps.archtag.outputs.tag }} -t docker.io/felsokning/worker-tools:${{ github.sha }}-arch .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/felsokning/worker-tools:${{ github.sha }}-arch'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'