name: Build and Publish Docker Image

# Required Since Release Creation in GitHub (itself) doesn't create a push (not remote)
on:
  release:
    types:
    - created

jobs:
  push_to_registry:
    name: Build and publish
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: /Alpine.3.19/Dockerfile
            image: felsokning/worker-tools
            tags: ${{ github.ref_name }}-alpine.3.19
          - dockerfile: /Arch/Dockerfile
            image: felsokning/worker-tools
            tags: ${{ github.ref_name }}-arch

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: felsokning
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ matrix.image }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ${{ github.workspace }}
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ matrix.tags }}
        labels: ${{ steps.meta.outputs.labels }}