name: Build and Publish Docker Image

# Required Since Release Creation in GitHub (itself) doesn't create a push (not remote)
on:
  release:
    types:
    - created

jobs:
  push_worker_tools_to_registry:
    name: Build and Publish Worker Tools
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Clean-Up Runner for Space
        run: |
          docker system prune --all --force
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/lib/android/sdk/ndk
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
      - name: Check out code
        uses: actions/checkout@v4.1.1
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: felsokning
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: felsokning/worker-tools
          flavor: |
            latest=false
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: packer_setup
        with:
          # Match Windows Version[s] for limited deviations
          version: "1.11.2"
      - name: Packer Init
        id: packer_init
        working-directory: ./packer
        run: |
          packer init -upgrade .
      - name: Packer Build
        working-directory: ./packer
        run: |
          packer build .
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ github.workspace }}/docker
          file: ./docker/Dockerfile
          push: true
          tags: felsokning/worker-tools:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}