name: Build and Trivy Scan Docker Images

on:
    pull_request:
      types: [ assigned, opened, synchronize, reopened ]

jobs:
    build_and_scan_alpine:
        name: Build and Scan Alpine
        runs-on: ubuntu-latest
        steps:
            - name: Space Clean-Up on Runner
              run: |
                sudo swapoff -a
                sudo rm -f /swapfile
                sudo apt clean
                docker rmi $(docker image ls -aq)
                df -h
                docker system prune --all --force
            - name: Check out code
              uses: actions/checkout@v4.1.1
            - name: Build Docker image
              shell: pwsh
              working-directory: ${{ github.workspace }}/Alpine.3.19/
              run: |
                docker build -t felsokning/worker-tools:${{ github.sha }}-alpine.3.19 .
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.19.0
              with:
                image-ref: 'docker.io/felsokning/worker-tools:${{ github.sha }}-alpine.3.19'
                # scan-type: 'image'
                format: 'sarif'
                output: '${{ github.sha }}-alpine-trivy-results.sarif'
            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: '${{ github.sha }}-alpine-trivy-results.sarif'
              